// Code generated by qtc from "accounts_users_index_turbo_stream.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamAccountsUsersIndexTurboStream(qw422016 *qt422016.Writer, ctx *ViewContext, users []UserSummary, nextPage *string) {
	qw422016.N().S(`<turbo-stream action="replace" target="next_page_container"><template>`)
	for i := range users {
		StreamAccountsUsersUser(qw422016, ctx, &users[i])
	}
	qw422016.N().S(`</template></turbo-stream>

`)
	if nextPage != nil {
		qw422016.N().S(`<turbo-stream action="append" target="account_users"><template>`)
		StreamAccountsUsersNextPageContainer(qw422016, *nextPage)
		qw422016.N().S(`</template></turbo-stream>
`)
	}
}

func WriteAccountsUsersIndexTurboStream(qq422016 qtio422016.Writer, ctx *ViewContext, users []UserSummary, nextPage *string) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamAccountsUsersIndexTurboStream(qw422016, ctx, users, nextPage)
	qt422016.ReleaseWriter(qw422016)
}

func AccountsUsersIndexTurboStream(ctx *ViewContext, users []UserSummary, nextPage *string) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteAccountsUsersIndexTurboStream(qb422016, ctx, users, nextPage)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
