// Code generated by qtc from "accounts_users_next_page_container.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamAccountsUsersNextPageContainer(qw422016 *qt422016.Writer, page string) {
	BeginCapture(qw422016)

	qw422016.N().S(`
  <div class="spinner center"></div>
`)
	capture1 := EndCapture(qw422016)

	qw422016.N().S(string(TurboFrameTag(capture1, "next_page_container", NewAttrs().Loading("lazy").Attr("src", "/account/users.turbo_stream?page="+CGIEscape(page)).Class("flex center"))))
}

func WriteAccountsUsersNextPageContainer(qq422016 qtio422016.Writer, page string) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamAccountsUsersNextPageContainer(qw422016, page)
	qt422016.ReleaseWriter(qw422016)
}

func AccountsUsersNextPageContainer(page string) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteAccountsUsersNextPageContainer(qb422016, page)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
