// Code generated by qtc from "accounts_users_user.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamAccountsUsersUser(qw422016 *qt422016.Writer, ctx *ViewContext, user *UserSummary) {
}

func WriteAccountsUsersUser(qq422016 qtio422016.Writer, ctx *ViewContext, user *UserSummary) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamAccountsUsersUser(qw422016, ctx, user)
	qt422016.ReleaseWriter(qw422016)
}

func AccountsUsersUser(ctx *ViewContext, user *UserSummary) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteAccountsUsersUser(qb422016, ctx, user)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
