// Code generated by qtc from "accounts_bots_bot.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamAccountsBotsBot(qw422016 *qt422016.Writer, ctx *ViewContext, bot *Bot) {
}

func WriteAccountsBotsBot(qq422016 qtio422016.Writer, ctx *ViewContext, bot *Bot) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamAccountsBotsBot(qw422016, ctx, bot)
	qt422016.ReleaseWriter(qw422016)
}

func AccountsBotsBot(ctx *ViewContext, bot *Bot) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteAccountsBotsBot(qb422016, ctx, bot)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
