// Code generated by qtc from "accounts_help_contact.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamAccountsHelpContact(qw422016 *qt422016.Writer, ctx *ViewContext, helpContact *HelpContact) {
}

func WriteAccountsHelpContact(qq422016 qtio422016.Writer, ctx *ViewContext, helpContact *HelpContact) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamAccountsHelpContact(qw422016, ctx, helpContact)
	qt422016.ReleaseWriter(qw422016)
}

func AccountsHelpContact(ctx *ViewContext, helpContact *HelpContact) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteAccountsHelpContact(qb422016, ctx, helpContact)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
