// Code generated by qtc from "accounts_bots_new.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func (p *AccountsBotsNew) StreamHead(qw422016 *qt422016.Writer) {
}

func (p *AccountsBotsNew) WriteHead(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamHead(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *AccountsBotsNew) Head() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteHead(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *AccountsBotsNew) StreamNav(qw422016 *qt422016.Writer) {
	qw422016.N().S(`  <div class="flex-item-justify-start">
    `)
	qw422016.N().S(string(LinkBackTo(p.Ctx, RouteAccountBots())))
	qw422016.N().S(`
  </div>
`)
}

func (p *AccountsBotsNew) WriteNav(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamNav(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *AccountsBotsNew) Nav() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteNav(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *AccountsBotsNew) StreamContent(qw422016 *qt422016.Writer) {
	qw422016.N().S(`<section class="panel">
`)
	form := FormWith(RouteAccountBots()).Model("user").Class("flex flex-column gap")

	qw422016.N().S(`  `)
	BeginCapture(qw422016)

	qw422016.N().S(`
    `)
	StreamAccountsBotsForm(qw422016, p.Ctx, form, &p.Bot)
	qw422016.N().S(`
`)
	capture1 := EndCapture(qw422016)

	qw422016.N().S(string(FormWithBlock(capture1, form)))
	qw422016.N().S(`</section>
`)
}

func (p *AccountsBotsNew) WriteContent(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamContent(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *AccountsBotsNew) Content() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteContent(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
