// Code generated by qtc from "accounts_bots_form.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamAccountsBotsForm(qw422016 *qt422016.Writer, ctx *ViewContext, form *Form, bot *BotForm) {
}

func WriteAccountsBotsForm(qq422016 qtio422016.Writer, ctx *ViewContext, form *Form, bot *BotForm) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamAccountsBotsForm(qw422016, ctx, form, bot)
	qt422016.ReleaseWriter(qw422016)
}

func AccountsBotsForm(ctx *ViewContext, form *Form, bot *BotForm) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteAccountsBotsForm(qb422016, ctx, form, bot)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
