// Code generated by qtc from "accounts_custom_styles_edit.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func (p *AccountsCustomStylesEdit) StreamHead(qw422016 *qt422016.Writer) {
}

func (p *AccountsCustomStylesEdit) WriteHead(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamHead(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *AccountsCustomStylesEdit) Head() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteHead(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *AccountsCustomStylesEdit) StreamNav(qw422016 *qt422016.Writer) {
	qw422016.N().S(`  <div class="flex-item-justify-start">
    `)
	qw422016.N().S(string(LinkBackTo(p.Ctx, RouteEditAccount())))
	qw422016.N().S(`
  </div>
`)
}

func (p *AccountsCustomStylesEdit) WriteNav(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamNav(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *AccountsCustomStylesEdit) Nav() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteNav(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *AccountsCustomStylesEdit) StreamContent(qw422016 *qt422016.Writer) {
	qw422016.N().S(`<section class="panel panel--wide txt-align-center flex flex-column position-relative" style="view-transition-name: custom-styles">
`)
	form := FormWith(p.Ctx.URL(RouteAccountCustomStyles())).Model("account").Method("patch").Class("flex flex-column gap").Data("controller", "form").Data("action", "keydown.ctrl+enter->form#submit keydown.meta+enter->form#submit")

	qw422016.N().S(`  `)
	BeginCapture(qw422016)

	qw422016.N().S(`
    <div class="panel__button">
      `)
	qw422016.N().S(string(TranslationButton(p.Ctx, "custom_styles")))
	qw422016.N().S(`
    </div>

    <div class="pad-inline-double margin-inline">
      <h1 class="margin-none">Custom CSS</h1>
      <p class="flex flex-wrap align-center justify-center gap margin-none-block-start" style="--column-gap: 0.5ch; --row-gap: 0">
        <span>Add custom CSS styles.</span>
        `)
	qw422016.N().S(string(ImageTag(p.Ctx, "alert.svg", NewAttrs().Class("flex-inline colorize--black").Size(16).AriaHidden())))
	qw422016.N().S(`
        <span>Use Caution: you could break things.</span>
      </p>
    </div>

    <label class="flex align-start gap flex-item-grow">
      `)
	qw422016.N().S(string(form.TextArea("custom_styles", p.CustomStyles, NewAttrs().Class("input input--code txt--small").Placeholder("Add CSS styles…").Autocomplete("off").Attr("spellcheck", "false").Attr("autocorrect", "off").Attr("autocapitalize", "off").Rows(16).Required(false))))
	qw422016.N().S(`
    </label>

    `)
	BeginCapture(qw422016)

	qw422016.N().S(`
      `)
	qw422016.N().S(string(ImageTag(p.Ctx, "check.svg", NewAttrs().AriaHidden().Size(20))))
	qw422016.N().S(`
      <span class="for-screen-reader">Save changes</span>
`)
	capture2 := EndCapture(qw422016)

	qw422016.N().S(string(Button(capture2, NewAttrs().Class("btn btn--reversed center txt-large").Type("submit"))))
	capture1 := EndCapture(qw422016)

	qw422016.N().S(string(FormWithBlock(capture1, form)))
	qw422016.N().S(`</section>
`)
}

func (p *AccountsCustomStylesEdit) WriteContent(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamContent(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *AccountsCustomStylesEdit) Content() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteContent(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
