// Code generated by qtc from "accounts_invite.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamAccountsInvite(qw422016 *qt422016.Writer, ctx *ViewContext, joinCode string) {
	qw422016.N().S(`<div class="flex flex-column align-center gap">
`)
	url := ctx.URL(RouteJoin(joinCode))

	qw422016.N().S(`
  <label class="flex flex-column gap full-width" style="--row-gap: 0.5em">
    <strong id="invite_label" class="invite-label">Share to invite more people</strong>
    <span class="flex align-center gap input input--actor fill-white">
      `)
	StreamImageTag(qw422016, ctx, "person-add.svg", NewAttrs().AriaHidden().Size(20).Class("colorize--black"))
	qw422016.N().S(`
      <input type="text" class="input" id="invite_url" value="`)
	qw422016.E().S(url)
	qw422016.N().S(`" aria-labelledby="invite_label" readonly>
    </span>
  </label>

  <div class="flex align-center gap">
    `)
	BeginCapture(qw422016)

	qw422016.N().S(`
      <span class="for-screen-reader">Show join link QR code</span>
      `)
	StreamImageTag(qw422016, ctx, "qr-code.svg", NewAttrs().AriaHidden().Size(20).Class("colorize--black"))
	qw422016.N().S(`
`)
	capture1 := EndCapture(qw422016)

	qw422016.N().S(string(LinkToZoomQrCode(capture1, url)))
	qw422016.N().S(`
    `)
	BeginCapture(qw422016)

	qw422016.N().S(`
      <span class="for-screen-reader">Copy join link</span>
      `)
	StreamImageTag(qw422016, ctx, "copy-paste.svg", NewAttrs().AriaHidden().Size(20).Class("colorize--black"))
	qw422016.N().S(`
`)
	capture2 := EndCapture(qw422016)

	qw422016.N().S(string(ButtonToCopyToClipboard(capture2, url)))
	qw422016.N().S(`
    `)
	BeginCapture(qw422016)

	qw422016.N().S(`
      <span class="for-screen-reader">Share join link</span>
      `)
	StreamImageTag(qw422016, ctx, "share.svg", NewAttrs().AriaHidden().Size(20).Class("colorize--black"))
	qw422016.N().S(`
`)
	capture3 := EndCapture(qw422016)

	qw422016.N().S(string(WebShareSessionButton(capture3, url, "Link to join Campfire", "Hit this link to join me in Campfire and start chatting.")))
	qw422016.N().S(`
`)
	if ctx.CanAdminister() {
		qw422016.N().S(`      `)
		BeginCapture(qw422016)

		qw422016.N().S(`
        `)
		StreamImageTag(qw422016, ctx, "refresh.svg", NewAttrs().AriaHidden().Size(20).Class("colorize--black"))
		qw422016.N().S(`
        <span class="for-screen-reader">Regenerate join link</span>
`)
		capture4 := EndCapture(qw422016)

		qw422016.N().S(string(ButtonToBlock(capture4, RouteAccountJoinCode(), NewAttrs().Class("btn btn--regenerate"))))
	}
	qw422016.N().S(`  </div>
</div>
`)
}

func WriteAccountsInvite(qq422016 qtio422016.Writer, ctx *ViewContext, joinCode string) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamAccountsInvite(qw422016, ctx, joinCode)
	qt422016.ReleaseWriter(qw422016)
}

func AccountsInvite(ctx *ViewContext, joinCode string) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteAccountsInvite(qb422016, ctx, joinCode)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
