// Code generated by qtc from "autocompletable_users_index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamAutocompletableUsersIndex(qw422016 *qt422016.Writer, ctx *ViewContext, users []MentionUser) {
	for i := range users {
		StreamAutocompletableUsersPromptItem(qw422016, ctx, &users[i])
	}
	qw422016.N().S(`
`)
}

func WriteAutocompletableUsersIndex(qq422016 qtio422016.Writer, ctx *ViewContext, users []MentionUser) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamAutocompletableUsersIndex(qw422016, ctx, users)
	qt422016.ReleaseWriter(qw422016)
}

func AutocompletableUsersIndex(ctx *ViewContext, users []MentionUser) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteAutocompletableUsersIndex(qb422016, ctx, users)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
