// Code generated by qtc from "layouts_lightbox.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamLayoutsLightbox(qw422016 *qt422016.Writer, ctx *ViewContext) {
	qw422016.N().S(`<dialog class="lightbox" aria-label="Image Viewer (Press escape to close)" data-lightbox-target="dialog" data-action="close->lightbox#reset">
  <img src="" class="lightbox__image" data-lightbox-target="zoomedImage" />

  <form method="dialog" class="lightbox__btn">
    <button class="btn">
      `)
	qw422016.N().S(string(ImageTag(ctx, "remove.svg", NewAttrs().AriaHidden())))
	qw422016.N().S(`
      <span class="for-screen-reader">Close image viewer</span>
    </button>
  </form>

  <a href="" class="lightbox__btn--download btn hide-in-ios-pwa" data-lightbox-target="download">
    `)
	qw422016.N().S(string(ImageTag(ctx, "download.svg", NewAttrs().AriaHidden())))
	qw422016.N().S(`
    <span class="for-screen-reader">Download file</span>
  </a>

  <button class="lightbox__btn--share btn"
      data-controller="web-share"
      data-action="web-share#share"
      data-web-share-files-value=""
      data-lightbox-target="share">
    `)
	qw422016.N().S(string(ImageTag(ctx, "share.svg", NewAttrs().AriaHidden())))
	qw422016.N().S(`
    <span class="for-screen-reader">Share file</span>
  </button>
</dialog>
`)
}

func WriteLayoutsLightbox(qq422016 qtio422016.Writer, ctx *ViewContext) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamLayoutsLightbox(qw422016, ctx)
	qt422016.ReleaseWriter(qw422016)
}

func LayoutsLightbox(ctx *ViewContext) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteLayoutsLightbox(qb422016, ctx)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
