// Code generated by qtc from "layouts_application_wrapper.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func (p *LayoutsApplicationWrapper) StreamHead(qw422016 *qt422016.Writer) {
	qw422016.N().S(string(p.HeadHTML))
}

func (p *LayoutsApplicationWrapper) WriteHead(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamHead(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *LayoutsApplicationWrapper) Head() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteHead(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *LayoutsApplicationWrapper) StreamNav(qw422016 *qt422016.Writer) {
	qw422016.N().S(string(p.NavHTML))
}

func (p *LayoutsApplicationWrapper) WriteNav(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamNav(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *LayoutsApplicationWrapper) Nav() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteNav(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *LayoutsApplicationWrapper) StreamContent(qw422016 *qt422016.Writer) {
	qw422016.N().S(string(p.ContentHTML))
}

func (p *LayoutsApplicationWrapper) WriteContent(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamContent(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *LayoutsApplicationWrapper) Content() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteContent(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *LayoutsApplicationWrapper) StreamFooter(qw422016 *qt422016.Writer) {
	qw422016.N().S(string(p.FooterHTML))
}

func (p *LayoutsApplicationWrapper) WriteFooter(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamFooter(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *LayoutsApplicationWrapper) Footer() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteFooter(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *LayoutsApplicationWrapper) StreamSidebar(qw422016 *qt422016.Writer) {
	qw422016.N().S(string(p.SidebarHTML))
}

func (p *LayoutsApplicationWrapper) WriteSidebar(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamSidebar(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *LayoutsApplicationWrapper) Sidebar() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteSidebar(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
