// Code generated by qtc from "layouts_application.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamLayoutsApplication(qw422016 *qt422016.Writer, ctx *ViewContext, p Page) {
	qw422016.N().S(`<!DOCTYPE html>
<html>
  <head>
    `)
	qw422016.N().S(string(PageTitleTag(p.PageTitle())))
	qw422016.N().S(`

    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no, interactive-widget=resizes-content">
    <meta name="view-transition" content="same-origin">
    <meta name="color-scheme" content="light dark">
    <meta name="theme-color" content="#ffffff" media="(prefers-color-scheme: light)">
    <meta name="theme-color" content="#000000" media="(prefers-color-scheme: dark)">
    <meta name="apple-mobile-web-app-capable" content="yes">
    `)
	qw422016.N().S(string(CurrentUserMetaTags(ctx)))
	qw422016.N().S(`
    `)
	qw422016.N().S(string(ScriptAwareActionCableMetaTag(ctx)))
	qw422016.N().S(`

    `)
	qw422016.N().S(string(BuilderTag("meta", NewAttrs().Name("vapid-public-key").AttrOpt("content", ctx.VAPIDPublicKey))))
	qw422016.N().S(`
    `)
	qw422016.N().S(string(BuilderTag("meta", NewAttrs().Name("turbo-prefetch").Attr("content", "true"))))
	qw422016.N().S(`

    `)
	qw422016.N().S(string(BuilderTag("link", NewAttrs().Attr("rel", "manifest").Attr("href", "/webmanifest.json"))))
	qw422016.N().S(`
    `)
	qw422016.N().S(string(BuilderTag("link", NewAttrs().Attr("rel", "icon").Attr("href", ctx.Account.LogoURL).Type("image/png"))))
	qw422016.N().S(`
    `)
	qw422016.N().S(string(BuilderTag("link", NewAttrs().Attr("rel", "apple-touch-icon").Attr("href", ctx.Account.LogoURL))))
	qw422016.N().S(`

    `)
	qw422016.N().S(string(ctx.StylesheetTags))
	qw422016.N().S(`
    `)
	qw422016.N().S(string(CustomStylesTag(ctx)))
	qw422016.N().S(`

    `)
	qw422016.N().S(string(ctx.ImportmapTags))
	qw422016.N().S(`

`)
	p.StreamHead(qw422016)
	qw422016.N().S(`  </head>

  <body class="`)
	qw422016.E().S(BodyClasses(ctx, p.BodyClass()))
	qw422016.N().S(`" data-controller="local-time lightbox">
    <a href="#main-content" class="skip-navigation btn">Skip to main content</a>

    <nav id="nav">
`)
	p.StreamNav(qw422016)
	qw422016.N().S(`    </nav>

`)
	notice := ctx.FlashNotice

	if notice == nil {
		notice = ctx.FlashAlert

	}
	if notice != nil {
		qw422016.N().S(`      <div class="flash" data-controller="element-removal" data-action="animationend->element-removal#remove">
        <div class="flash__inner shadow" style="`)
		if ctx.FlashAlert != nil {
			qw422016.N().S(`--flash-background: var(--color-negative)`)
		}
		qw422016.N().S(`">
`)
		if ctx.FlashAlert != nil {
			qw422016.N().S(`            `)
			qw422016.N().S(string(ImageTag(ctx, "alert.svg", NewAttrs().Aria("hidden", true).Size(24).Class("colorize--white"))))
			qw422016.N().S(`</span>
`)
		} else {
			qw422016.N().S(`            `)
			qw422016.N().S(string(ImageTag(ctx, "check.svg", NewAttrs().Aria("hidden", true).Size(24).Class("colorize--white"))))
			qw422016.N().S(`</span>
`)
		}
		qw422016.N().S(`        </div>
        <span class="for-screen-reader" role="alert" aria-atomic="true">`)
		qw422016.E().S(*notice)
		qw422016.N().S(`</span>
      </div>
`)
	}
	qw422016.N().S(`
    <main id="main-content">
`)
	p.StreamContent(qw422016)
	qw422016.N().S(`
      <footer id="footer">
`)
	p.StreamFooter(qw422016)
	qw422016.N().S(`      </footer>
    </main>

    <aside id="sidebar" data-controller="toggle-class" data-toggle-class-toggle-class="open">
`)
	p.StreamSidebar(qw422016)
	qw422016.N().S(`    </aside>

    `)
	StreamLayoutsLightbox(qw422016, ctx)
	qw422016.N().S(`

    <a href="https://once.com" id="app-logo" target="_blank" aria-label="Once software from 37signals home page">
      `)
	qw422016.N().S(string(ImageTag(ctx, "campfire-icon.png", NewAttrs().Alt("Campfire logo").Attr("width", 256).Attr("height", 216))))
	qw422016.N().S(`
    </a>
  </body>
</html>
`)
}

func WriteLayoutsApplication(qq422016 qtio422016.Writer, ctx *ViewContext, p Page) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamLayoutsApplication(qw422016, ctx, p)
	qt422016.ReleaseWriter(qw422016)
}

func LayoutsApplication(ctx *ViewContext, p Page) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteLayoutsApplication(qb422016, ctx, p)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
