// Code generated by qtc from "layouts_turbo_rails_frame.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamLayoutsTurboRailsFrame(qw422016 *qt422016.Writer, ctx *ViewContext, p Page) {
	qw422016.N().S(`<html>
  <head>
    `)
	p.StreamHead(qw422016)
	qw422016.N().S(`
  </head>
  <body>
    `)
	p.StreamContent(qw422016)
	qw422016.N().S(`
  </body>
</html>
`)
}

func WriteLayoutsTurboRailsFrame(qq422016 qtio422016.Writer, ctx *ViewContext, p Page) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamLayoutsTurboRailsFrame(qw422016, ctx, p)
	qt422016.ReleaseWriter(qw422016)
}

func LayoutsTurboRailsFrame(ctx *ViewContext, p Page) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteLayoutsTurboRailsFrame(qb422016, ctx, p)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
