// Code generated by qtc from "messages_template.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamMessagesTemplate(qw422016 *qt422016.Writer, ctx *ViewContext, user *UserView) {
}

func WriteMessagesTemplate(qq422016 qtio422016.Writer, ctx *ViewContext, user *UserView) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamMessagesTemplate(qw422016, ctx, user)
	qt422016.ReleaseWriter(qw422016)
}

func MessagesTemplate(ctx *ViewContext, user *UserView) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteMessagesTemplate(qb422016, ctx, user)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
