// Code generated by qtc from "messages_create_turbo_stream.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamMessagesCreateTurboStream(qw422016 *qt422016.Writer, ctx *ViewContext, message MessageItem, roomKind RoomKind) {
	qw422016.N().S(`<turbo-stream action="append" target="`)
	qw422016.E().S(RoomDomID(roomKind, message.RoomID(), "messages"))
	qw422016.N().S(`"><template>`)
	StreamFragment(qw422016, CachedMessageItem(ctx, message))
	qw422016.N().S(`</template></turbo-stream>`)
}

func WriteMessagesCreateTurboStream(qq422016 qtio422016.Writer, ctx *ViewContext, message MessageItem, roomKind RoomKind) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamMessagesCreateTurboStream(qw422016, ctx, message, roomKind)
	qt422016.ReleaseWriter(qw422016)
}

func MessagesCreateTurboStream(ctx *ViewContext, message MessageItem, roomKind RoomKind) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteMessagesCreateTurboStream(qb422016, ctx, message, roomKind)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
