// Code generated by qtc from "messages_unrenderable.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamMessagesUnrenderable(qw422016 *qt422016.Writer) {
}

func WriteMessagesUnrenderable(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamMessagesUnrenderable(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func MessagesUnrenderable() string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteMessagesUnrenderable(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
