// Code generated by qtc from "messages_destroy_turbo_stream.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamMessagesDestroyTurboStream(qw422016 *qt422016.Writer, message *MessageView) {
}

func WriteMessagesDestroyTurboStream(qq422016 qtio422016.Writer, message *MessageView) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamMessagesDestroyTurboStream(qw422016, message)
	qt422016.ReleaseWriter(qw422016)
}

func MessagesDestroyTurboStream(message *MessageView) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteMessagesDestroyTurboStream(qb422016, message)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
