// Code generated by qtc from "messages_edit.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamMessagesEdit(qw422016 *qt422016.Writer, ctx *ViewContext, edit *MessageEditView) {
}

func WriteMessagesEdit(qq422016 qtio422016.Writer, ctx *ViewContext, edit *MessageEditView) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamMessagesEdit(qw422016, ctx, edit)
	qt422016.ReleaseWriter(qw422016)
}

func MessagesEdit(ctx *ViewContext, edit *MessageEditView) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteMessagesEdit(qb422016, ctx, edit)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
