// Code generated by qtc from "messages_boosts_index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamMessagesBoostsIndex(qw422016 *qt422016.Writer, ctx *ViewContext, message *MessageView) {
	StreamMessagesBoostsBoosts(qw422016, ctx, message)
}

func WriteMessagesBoostsIndex(qq422016 qtio422016.Writer, ctx *ViewContext, message *MessageView) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamMessagesBoostsIndex(qw422016, ctx, message)
	qt422016.ReleaseWriter(qw422016)
}

func MessagesBoostsIndex(ctx *ViewContext, message *MessageView) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteMessagesBoostsIndex(qb422016, ctx, message)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
