// Code generated by qtc from "messages_boosts_boost.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamMessagesBoostsBoost(qw422016 *qt422016.Writer, ctx *ViewContext, boost *BoostView) {
}

func WriteMessagesBoostsBoost(qq422016 qtio422016.Writer, ctx *ViewContext, boost *BoostView) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamMessagesBoostsBoost(qw422016, ctx, boost)
	qt422016.ReleaseWriter(qw422016)
}

func MessagesBoostsBoost(ctx *ViewContext, boost *BoostView) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteMessagesBoostsBoost(qb422016, ctx, boost)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
