// Code generated by qtc from "messages_presentation.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamMessagesPresentation(qw422016 *qt422016.Writer, ctx *ViewContext, message *MessageView) {
	qw422016.N().S(`<div id="`)
	qw422016.E().S(message.DomID("presentation"))
	qw422016.N().S(`" dir="auto" data-reply-target="body" data-messages-target="body">
  `)
	qw422016.N().S(string(MessagePresentation(ctx, message)))
	qw422016.N().S(`
</div>`)
}

func WriteMessagesPresentation(qq422016 qtio422016.Writer, ctx *ViewContext, message *MessageView) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamMessagesPresentation(qw422016, ctx, message)
	qt422016.ReleaseWriter(qw422016)
}

func MessagesPresentation(ctx *ViewContext, message *MessageView) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteMessagesPresentation(qb422016, ctx, message)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
