// Code generated by qtc from "messages_room_not_found.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamMessagesRoomNotFound(qw422016 *qt422016.Writer) {
	qw422016.N().S(`<turbo-frame id="composer-frame">
  <span class="composer__input input input--actor shake margin-block-end txt-negative txt-align-center" style="--input-border-color: var(--color-negative)">
      <span>This room was deleted.</span>
  </span>
</turbo-frame>`)
}

func WriteMessagesRoomNotFound(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamMessagesRoomNotFound(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func MessagesRoomNotFound() string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteMessagesRoomNotFound(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
