package views

// Every page type renders in the application layout.
var (
	_ Page = (*AccountsBotsEdit)(nil)
	_ Page = (*AccountsBotsIndex)(nil)
	_ Page = (*AccountsBotsNew)(nil)
	_ Page = (*AccountsCustomStylesEdit)(nil)
	_ Page = (*AccountsEdit)(nil)
	_ Page = (*FirstRunsShow)(nil)
	_ Page = (*RoomsClosedsEdit)(nil)
	_ Page = (*RoomsClosedsNew)(nil)
	_ Page = (*RoomsDirectsEdit)(nil)
	_ Page = (*RoomsDirectsNew)(nil)
	_ Page = (*RoomsLayoutsEdit)(nil)
	_ Page = (*RoomsLayoutsNew)(nil)
	_ Page = (*RoomsOpensEdit)(nil)
	_ Page = (*RoomsOpensNew)(nil)
	_ Page = (*RoomsShow)(nil)
	_ Page = (*SearchesIndex)(nil)
	_ Page = (*SessionsIncompatibleBrowser)(nil)
	_ Page = (*SessionsNew)(nil)
	_ Page = (*SessionsTransfersShow)(nil)
	_ Page = (*UsersNew)(nil)
	_ Page = (*UsersProfilesShow)(nil)
	_ Page = (*UsersPushSubscriptionsIndex)(nil)
	_ Page = (*UsersShow)(nil)
	_ Page = (*UsersSidebarsShow)(nil)
	_ Page = (*WelcomeShow)(nil)

	_ RoomFormPage = (*RoomsClosedsEdit)(nil)
	_ RoomFormPage = (*RoomsClosedsNew)(nil)
	_ RoomFormPage = (*RoomsOpensEdit)(nil)
	_ RoomFormPage = (*RoomsOpensNew)(nil)
)
