// Code generated by qtc from "pwa_manifest_json.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamPwaManifestJson(qw422016 *qt422016.Writer, accountName *string, logoPathSmall, logoPath, baseURL string, assetPath func(string) string) {
}

func WritePwaManifestJson(qq422016 qtio422016.Writer, accountName *string, logoPathSmall, logoPath, baseURL string, assetPath func(string) string) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamPwaManifestJson(qw422016, accountName, logoPathSmall, logoPath, baseURL, assetPath)
	qt422016.ReleaseWriter(qw422016)
}

func PwaManifestJson(accountName *string, logoPathSmall, logoPath, baseURL string, assetPath func(string) string) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WritePwaManifestJson(qb422016, accountName, logoPathSmall, logoPath, baseURL, assetPath)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
