// Code generated by qtc from "pwa_system_settings.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamPwaSystemSettings(qw422016 *qt422016.Writer, ctx *ViewContext) {
}

func WritePwaSystemSettings(qq422016 qtio422016.Writer, ctx *ViewContext) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamPwaSystemSettings(qw422016, ctx)
	qt422016.ReleaseWriter(qw422016)
}

func PwaSystemSettings(ctx *ViewContext) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WritePwaSystemSettings(qb422016, ctx)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
