// Code generated by qtc from "pwa_browser_settings.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamPwaBrowserSettings(qw422016 *qt422016.Writer, ctx *ViewContext) {
}

func WritePwaBrowserSettings(qq422016 qtio422016.Writer, ctx *ViewContext) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamPwaBrowserSettings(qw422016, ctx)
	qt422016.ReleaseWriter(qw422016)
}

func PwaBrowserSettings(ctx *ViewContext) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WritePwaBrowserSettings(qb422016, ctx)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
