// Code generated by qtc from "rooms_opens_user.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamRoomsOpensUser(qw422016 *qt422016.Writer, ctx *ViewContext, form *OpenFormView, user *UserView) {
	qw422016.N().S(`<li class="flex align-center gap margin-none" data-value="`)
	qw422016.E().S(Lowercase(user.Name))
	qw422016.N().S(`">
  <figure class="avatar flex-item-no-shrink" style="--avatar-size: 4ch;">
    <a title="`)
	qw422016.E().S(user.Title)
	qw422016.N().S(`" class="btn avatar" data-turbo-frame="_top" href="`)
	qw422016.E().S(user.Path())
	qw422016.N().S(`"><img aria-hidden="true" loading="lazy" src="`)
	qw422016.E().S(user.AvatarURL)
	qw422016.N().S(`" width="48" height="48" /></a>
  </figure>

  <div class="min-width">
    <div class="overflow-ellipsis fill-shade"><strong>`)
	qw422016.E().S(user.Name)
	qw422016.N().S(`</strong></div>
  </div>

  <hr class="separator" aria-hidden="true">`)
	if form.CanAdminister {
		qw422016.N().S(`
    <img class="colorize--black flex-item-no-shrink" aria-hidden="true" src="`)
		qw422016.E().S(ctx.Asset("check.svg"))
		qw422016.N().S(`" width="20" height="20" />`)
	}
	qw422016.N().S(`
</li>`)
}

func WriteRoomsOpensUser(qq422016 qtio422016.Writer, ctx *ViewContext, form *OpenFormView, user *UserView) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamRoomsOpensUser(qw422016, ctx, form, user)
	qt422016.ReleaseWriter(qw422016)
}

func RoomsOpensUser(ctx *ViewContext, form *OpenFormView, user *UserView) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteRoomsOpensUser(qb422016, ctx, form, user)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
