// Code generated by qtc from "rooms_show_invitation.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamRoomsShowInvitation(qw422016 *qt422016.Writer, ctx *ViewContext, joinCode string) {
	qw422016.N().S(`<div id="system_welcome" class="message message--formatted txt-align-center center">
    <div class="message__body center">
      <div class="message__body-content position-relative">
        `)
	qw422016.N().S(string(AccountLogoTag(ctx, "center margin-block-end txt-large")))
	qw422016.N().S(`
        <div class="flex align-center gap">
          <div class="system-welcome--translation">
            `)
	qw422016.N().S(string(TranslationButton(ctx, "invite_message")))
	qw422016.N().S(`
          </div>
          <p>
            <strong>Welcome to Campfire</strong><br>
            To invite people to chat, share the join link below.
          </p>
        </div>
        `)
	StreamAccountsInvite(qw422016, ctx, joinCode)
	qw422016.N().S(`
      </div>
    </div>
  </div>`)
}

func WriteRoomsShowInvitation(qq422016 qtio422016.Writer, ctx *ViewContext, joinCode string) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamRoomsShowInvitation(qw422016, ctx, joinCode)
	qt422016.ReleaseWriter(qw422016)
}

func RoomsShowInvitation(ctx *ViewContext, joinCode string) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteRoomsShowInvitation(qb422016, ctx, joinCode)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
