// Code generated by qtc from "rooms_layouts_edit.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func (p *RoomsLayoutsEdit) StreamHead(qw422016 *qt422016.Writer) {
}

func (p *RoomsLayoutsEdit) WriteHead(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamHead(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *RoomsLayoutsEdit) Head() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteHead(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *RoomsLayoutsEdit) StreamNav(qw422016 *qt422016.Writer) {
	qw422016.N().S(`
  <div class="flex-item-justify-start">
    `)
	qw422016.N().S(string(LinkBackToLastRoomVisited(p.Ctx)))
	qw422016.N().S(`
  </div>`)
}

func (p *RoomsLayoutsEdit) WriteNav(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamNav(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *RoomsLayoutsEdit) Nav() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteNav(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *RoomsLayoutsEdit) StreamContent(qw422016 *qt422016.Writer) {
	qw422016.N().S(`
<section class="panel txt-align-center" style="view-transition-name: edit-room-`)
	qw422016.N().DL(p.RoomID())
	qw422016.N().S(`">
  `)
	p.Page.StreamRoomForm(qw422016)
	qw422016.N().S(`
</section>`)
	if p.CanAdminister {
		qw422016.N().S(`
  <section class="panel txt-align-center">
    `)
		qw422016.N().S(string(ButtonToDeleteRoom(p.Ctx, p.RoomID(), p.Room.DisplayName())))
		qw422016.N().S(`
  </section>`)
	}
}

func (p *RoomsLayoutsEdit) WriteContent(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamContent(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *RoomsLayoutsEdit) Content() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteContent(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
