// Code generated by qtc from "rooms_refreshes_show_turbo_stream.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamRoomsRefreshesShowTurboStream(qw422016 *qt422016.Writer, ctx *ViewContext, refresh *RefreshView) {
}

func WriteRoomsRefreshesShowTurboStream(qq422016 qtio422016.Writer, ctx *ViewContext, refresh *RefreshView) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamRoomsRefreshesShowTurboStream(qw422016, ctx, refresh)
	qt422016.ReleaseWriter(qw422016)
}

func RoomsRefreshesShowTurboStream(ctx *ViewContext, refresh *RefreshView) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteRoomsRefreshesShowTurboStream(qb422016, ctx, refresh)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
