// Code generated by qtc from "rooms_closeds_edit.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func (p *RoomsClosedsEdit) StreamRoomForm(qw422016 *qt422016.Writer) {
	StreamRoomsClosedsForm(qw422016, p.Ctx, p.Form, RouteEditRoomsOpen(p.RoomID()))
}

func (p *RoomsClosedsEdit) WriteRoomForm(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamRoomForm(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *RoomsClosedsEdit) RoomForm() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteRoomForm(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
