// Code generated by qtc from "rooms_show_composer.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamRoomsShowComposer(qw422016 *qt422016.Writer, ctx *ViewContext, room *RoomView) {
	qw422016.N().S(`<div class="composer flex align-end gap position-relative"
      data-controller="typing-notifications" data-typing-notifications-active-class="typing-indicator--active">
    <a class="btn flex-item-no-shrink margin-block-end composer__context-btn" style="view-transition-name: input-switcher" href="`)
	qw422016.E().S(RouteSearches())
	qw422016.N().S(`">
      <img aria-hidden="true" src="`)
	qw422016.E().S(ctx.Asset("search.svg"))
	qw422016.N().S(`" width="20" height="20" />
      <span class="for-screen-reader">Search</span>
</a>
    <turbo-frame id="composer-frame">
      <form id="composer" class="margin-block flex-item-grow contain" data-controller="composer drop-target" data-action="dragenter-&gt;drop-target#dragenter dragover-&gt;drop-target#dragover drop-&gt;drop-target#drop drop-target:drop@window-&gt;composer#dropFiles lexxy:file-accept-&gt;composer#preventAttachment refresh-room:online@window-&gt;composer#online typing-notifications#stop paste-&gt;composer#pasteFiles turbo:submit-end-&gt;composer#submitEnd refresh-room:offline@window-&gt;composer#offline" data-composer-messages-outlet="#message-area" data-composer-toolbar-class="composer--rich-text" data-composer-room-id-value="`)
	qw422016.N().DL(room.ID)
	qw422016.N().S(`" action="`)
	qw422016.E().S(RouteRoomMessages(room.ID))
	qw422016.N().S(`" accept-charset="UTF-8" method="post">
        <fieldset data-composer-target="fields" contents>
          <div class="flex flex-column">
            <div class="composer__filelist flex flex--align-center gap flex-wrap" data-composer-target="fileList"></div>

            <div class="flex composer__input input input--actor fill-white min-width" style="--input-border-radius: 1.3rem">
              <div class="flex align-end gap full-width">
                <img aria-hidden="true" class="composer__input-hint colorize--black" style="view-transition-name: input-btn;" src="`)
	qw422016.E().S(ctx.Asset("messages-outlined.svg"))
	qw422016.N().S(`" width="22" height="22" />

                <div class="flex flex-column flex-item-grow min-width gap">
                  <lexxy-editor rows="1" class="input lexxy-content" style="order: -1" aria-multiline="true" aria-label="Write a message" permitted-attachment-types="application/vnd.campfire.mention application/vnd.actiontext.opengraph-embed" data-controller="unfurl" data-action="lexxy:change-&gt;typing-notifications#start keydown-&gt;composer#submitByKeyboard:capture lexxy:change-&gt;composer#saveDraft lexxy:insert-link-&gt;unfurl#unfurl" data-composer-target="text" data-direct-upload-url="`)
	qw422016.E().S(ctx.URL("/rails/active_storage/direct_uploads"))
	qw422016.N().S(`" data-blob-url-template="`)
	qw422016.E().S(ctx.URL("/rails/active_storage/blobs/redirect/:signed_id/:filename"))
	qw422016.N().S(`" id="message_body" input="message_body_trix_input_message" name="message[body]">
                    <lexxy-prompt trigger="@" name="mention" src="`)
	qw422016.E().S(MentionPromptSrc(room.ID))
	qw422016.N().S(`" remote-filtering="true" empty-results="No matches"></lexxy-prompt>
</lexxy-editor>                </div>

                <label class="btn btn--borderless txt-small flex-item-no-shrink composer__attachment-btn input--file">
                  <img class="colorize--black" aria-hidden="true" src="`)
	qw422016.E().S(ctx.Asset("attachment.svg"))
	qw422016.N().S(`" width="22" height="22" />
                  <input type="file" data-action="composer#filePicked" multiple />
                  <span class="for-screen-reader">Attach a file</span>
                </label>

                <button class="btn btn--borderless txt-small flex-item-no-shrink composer__rich-text-btn" type="button" data-action="composer#toggleToolbar">
                  <img class="colorize--black" aria-hidden="true" src="`)
	qw422016.E().S(ctx.Asset("text-options.svg"))
	qw422016.N().S(`" width="20" height="20" />
                  <span class="for-screen-reader">Rich text</span>
                </button>

                <button name="send" type="submit" data-action="composer#submit" class="btn btn--reversed flex-item-no-shrink txt-small">
                  <img aria-hidden="true" src="`)
	qw422016.E().S(ctx.Asset("arrow-up.svg"))
	qw422016.N().S(`" width="20" height="20" />
                  <span class="for-screen-reader">Send Message</span>
</button>              </div>
            </div>
          </div>
        </fieldset>

        <div class="typing-indicator gap txt-small align-center flex-inline" data-typing-notifications-target="indicator">
          <div class="typing-indicator__author spinner" data-typing-notifications-target="author"></div>
        </div>

        <input data-composer-target="clientid" type="hidden" name="message[client_message_id]" id="message_client_message_id" />
</form>    </turbo-frame>
  </div>`)
}

func WriteRoomsShowComposer(qq422016 qtio422016.Writer, ctx *ViewContext, room *RoomView) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamRoomsShowComposer(qw422016, ctx, room)
	qt422016.ReleaseWriter(qw422016)
}

func RoomsShowComposer(ctx *ViewContext, room *RoomView) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteRoomsShowComposer(qb422016, ctx, room)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
