// Code generated by qtc from "rooms_show_composer.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamRoomsShowComposer(qw422016 *qt422016.Writer, ctx *ViewContext, room *RoomView) {
}

func WriteRoomsShowComposer(qq422016 qtio422016.Writer, ctx *ViewContext, room *RoomView) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamRoomsShowComposer(qw422016, ctx, room)
	qt422016.ReleaseWriter(qw422016)
}

func RoomsShowComposer(ctx *ViewContext, room *RoomView) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteRoomsShowComposer(qb422016, ctx, room)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
