// Code generated by qtc from "rooms_involvements_show.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamRoomsInvolvementsShow(qw422016 *qt422016.Writer, ctx *ViewContext, involvement *InvolvementView) {
}

func WriteRoomsInvolvementsShow(qq422016 qtio422016.Writer, ctx *ViewContext, involvement *InvolvementView) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamRoomsInvolvementsShow(qw422016, ctx, involvement)
	qt422016.ReleaseWriter(qw422016)
}

func RoomsInvolvementsShow(ctx *ViewContext, involvement *InvolvementView) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteRoomsInvolvementsShow(qb422016, ctx, involvement)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
