// Code generated by qtc from "rooms_layouts_form.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamRoomsLayoutsForm(qw422016 *qt422016.Writer, ctx *ViewContext, room *FormRoom, canAdminister bool, kind RoomKind, content HTML) {
}

func WriteRoomsLayoutsForm(qq422016 qtio422016.Writer, ctx *ViewContext, room *FormRoom, canAdminister bool, kind RoomKind, content HTML) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamRoomsLayoutsForm(qw422016, ctx, room, canAdminister, kind, content)
	qt422016.ReleaseWriter(qw422016)
}

func RoomsLayoutsForm(ctx *ViewContext, room *FormRoom, canAdminister bool, kind RoomKind, content HTML) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteRoomsLayoutsForm(qb422016, ctx, room, canAdminister, kind, content)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
