// Code generated by qtc from "rooms_show_invitation.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamRoomsShowInvitation(qw422016 *qt422016.Writer, ctx *ViewContext, joinCode string) {
}

func WriteRoomsShowInvitation(qq422016 qtio422016.Writer, ctx *ViewContext, joinCode string) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamRoomsShowInvitation(qw422016, ctx, joinCode)
	qt422016.ReleaseWriter(qw422016)
}

func RoomsShowInvitation(ctx *ViewContext, joinCode string) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteRoomsShowInvitation(qb422016, ctx, joinCode)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
