// Code generated by qtc from "rooms_closeds_user.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamRoomsClosedsUser(qw422016 *qt422016.Writer, ctx *ViewContext, form *ClosedFormView, user *UserView, selected bool) {
}

func WriteRoomsClosedsUser(qq422016 qtio422016.Writer, ctx *ViewContext, form *ClosedFormView, user *UserView, selected bool) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamRoomsClosedsUser(qw422016, ctx, form, user, selected)
	qt422016.ReleaseWriter(qw422016)
}

func RoomsClosedsUser(ctx *ViewContext, form *ClosedFormView, user *UserView, selected bool) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteRoomsClosedsUser(qb422016, ctx, form, user, selected)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
