// Code generated by qtc from "rooms_opens_form.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamRoomsOpensForm(qw422016 *qt422016.Writer, ctx *ViewContext, form *OpenFormView, typeChangePath string) {
}

func WriteRoomsOpensForm(qq422016 qtio422016.Writer, ctx *ViewContext, form *OpenFormView, typeChangePath string) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamRoomsOpensForm(qw422016, ctx, form, typeChangePath)
	qt422016.ReleaseWriter(qw422016)
}

func RoomsOpensForm(ctx *ViewContext, form *OpenFormView, typeChangePath string) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteRoomsOpensForm(qb422016, ctx, form, typeChangePath)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
