// Code generated by qtc from "searches_recents.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamSearchesRecents(qw422016 *qt422016.Writer, ctx *ViewContext, index *SearchIndexView) {
}

func WriteSearchesRecents(qq422016 qtio422016.Writer, ctx *ViewContext, index *SearchIndexView) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamSearchesRecents(qw422016, ctx, index)
	qt422016.ReleaseWriter(qw422016)
}

func SearchesRecents(ctx *ViewContext, index *SearchIndexView) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteSearchesRecents(qb422016, ctx, index)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
