// Code generated by qtc from "searches_recents.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamSearchesRecents(qw422016 *qt422016.Writer, ctx *ViewContext, index *SearchIndexView) {
	for _, search := range index.RecentSearches {
		qw422016.N().S(`
      <a class="align-center gap room btn txt-nowrap" href="`)
		qw422016.E().S(SearchPath(search))
		qw422016.N().S(`">
        <span class="overflow-ellipsis">“`)
		qw422016.E().S(search)
		qw422016.N().S(`”</span>
</a>`)
	}
	if len(index.RecentSearches) > 0 {
		qw422016.N().S(`
      <form class="button_to" method="post" action="`)
		qw422016.E().S(ctx.URL(RouteClearSearches()))
		qw422016.N().S(`"><input type="hidden" name="_method" value="delete" /><button class="btn searches__btn" data-turbo-confirm="Are you sure you want to clear your recent searches?" type="submit">
        <img aria-hidden="true" src="`)
		qw422016.E().S(ctx.Asset("broom.svg"))
		qw422016.N().S(`" />
        <span class="for-screen-reader">Clear recent searches</span>
</button></form>`)
	}
}

func WriteSearchesRecents(qq422016 qtio422016.Writer, ctx *ViewContext, index *SearchIndexView) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamSearchesRecents(qw422016, ctx, index)
	qt422016.ReleaseWriter(qw422016)
}

func SearchesRecents(ctx *ViewContext, index *SearchIndexView) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteSearchesRecents(qb422016, ctx, index)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
