// Code generated by qtc from "sessions_transfers_show.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func (p *SessionsTransfersShow) StreamHead(qw422016 *qt422016.Writer) {
}

func (p *SessionsTransfersShow) WriteHead(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamHead(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *SessionsTransfersShow) Head() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteHead(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *SessionsTransfersShow) StreamContent(qw422016 *qt422016.Writer) {
	qw422016.N().S(`
`)
	qw422016.N().S(string(FormWith(p.Action).Method("put").AutoSubmit().Open()))
	qw422016.N().S(`
`)
}

func (p *SessionsTransfersShow) WriteContent(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamContent(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *SessionsTransfersShow) Content() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteContent(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
