// Code generated by qtc from "users_profiles_membership.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamUsersProfilesMembership(qw422016 *qt422016.Writer, ctx *ViewContext, membership *ProfileMembership) {
	qw422016.N().S(`<li class="flex align-center gap margin-none min-width membership-item">
  `)
	BeginCapture(qw422016)

	qw422016.N().S(`
    <strong>`)
	qw422016.E().S(membership.RoomDisplayName)
	qw422016.N().S(`</strong>
`)
	capture1 := EndCapture(qw422016)

	qw422016.N().S(string(LinkToBlock(capture1, RouteRoom(membership.RoomID), NewAttrs().Class("overflow-ellipsis fill-shade txt-primary txt-undecorated"))))
	qw422016.N().S(`
  <hr class="separator" aria-hidden="true">

  <span class="txt-small">
    `)
	BeginCapture(qw422016)

	qw422016.N().S(`
      `)
	qw422016.N().S(string(ButtonToChangeInvolvement(ctx, membership.InvolvementRoom(), membership.Involvement)))
	qw422016.N().S(`
`)
	capture2 := EndCapture(qw422016)

	qw422016.N().S(string(TurboFrameTag(capture2, DomID(membership.RoomParamKey, membership.RoomID, "involvement"), NewAttrs())))
	qw422016.N().S(`  </span>
</li>
`)
}

func WriteUsersProfilesMembership(qq422016 qtio422016.Writer, ctx *ViewContext, membership *ProfileMembership) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamUsersProfilesMembership(qw422016, ctx, membership)
	qt422016.ReleaseWriter(qw422016)
}

func UsersProfilesMembership(ctx *ViewContext, membership *ProfileMembership) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteUsersProfilesMembership(qb422016, ctx, membership)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
