// Code generated by qtc from "users_mention.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamUsersMention(qw422016 *qt422016.Writer, ctx *ViewContext, user *MentionUser) {
}

func WriteUsersMention(qq422016 qtio422016.Writer, ctx *ViewContext, user *MentionUser) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamUsersMention(qw422016, ctx, user)
	qt422016.ReleaseWriter(qw422016)
}

func UsersMention(ctx *ViewContext, user *MentionUser) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteUsersMention(qb422016, ctx, user)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
