// Code generated by qtc from "users_sidebars_rooms_shared.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamUsersSidebarsRoomsShared(qw422016 *qt422016.Writer, room *SidebarRoom) {
	BeginCapture(qw422016)

	qw422016.N().S(`
  <span class="overflow-ellipsis">`)
	qw422016.E().S(room.Name)
	qw422016.N().S(`</span>
`)
	EndCaptureLinkToRoom(qw422016, room.ID, NewAttrs().ID(DomID(room.ParamKey, room.ID, "list")).Data("sorted_list_name", room.Name).Style("--column-gap: 0.5em").Class(room.ClassNames()))

}

func WriteUsersSidebarsRoomsShared(qq422016 qtio422016.Writer, room *SidebarRoom) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamUsersSidebarsRoomsShared(qw422016, room)
	qt422016.ReleaseWriter(qw422016)
}

func UsersSidebarsRoomsShared(room *SidebarRoom) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteUsersSidebarsRoomsShared(qb422016, room)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
