// Code generated by qtc from "users_new.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func (p *UsersNew) StreamHead(qw422016 *qt422016.Writer) {
}

func (p *UsersNew) WriteHead(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamHead(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *UsersNew) Head() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteHead(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *UsersNew) StreamNav(qw422016 *qt422016.Writer) {
	qw422016.N().S(`  <div class="flex-item-justify-end">
    `)
	BeginCapture(qw422016)

	qw422016.N().S(`
      `)
	qw422016.N().S(string(ImageTag(p.Ctx, "login-keys.svg", NewAttrs().AriaHidden())))
	qw422016.N().S(`
      <span class="for-screen-reader">Sign in</span>
`)
	capture1 := EndCapture(qw422016)

	qw422016.N().S(string(LinkToBlock(capture1, RouteNewSession(), NewAttrs().Class("btn flex-item-justify-end"))))
	qw422016.N().S(`  </div>
`)
}

func (p *UsersNew) WriteNav(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamNav(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *UsersNew) Nav() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteNav(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *UsersNew) StreamContent(qw422016 *qt422016.Writer) {
	form := FormWith(RouteJoin(p.JoinCode)).Model("user").Class("center")

	BeginCapture(qw422016)

	qw422016.N().S(`
  <section class="nametag u-relative">
    <div class="flex justify-center align-center pad-block">
      `)
	qw422016.N().S(string(ImageTag(p.Ctx, "lanyard.svg", NewAttrs().Class("nametag__lanyard").AriaHidden())))
	qw422016.N().S(`
    </div>

    <div class="nametag__inner flex flex-column gap">
      <fieldset class="flex flex-column center-block">
        <legend class="txt-align-center flex gap">
          `)
	qw422016.N().S(string(AccountLogoTag(p.Ctx, "")))
	qw422016.N().S(`
          <strong class="txt-large">`)
	qw422016.E().S(p.Ctx.Account.Name)
	qw422016.N().S(`</strong>
        </legend>

        <label class="align-center center avatar__form gap" data-controller="upload-preview">
          <div class="btn input--file">
            `)
	qw422016.N().S(string(ImageTag(p.Ctx, "camera.svg", NewAttrs().AriaHidden())))
	qw422016.N().S(`
            `)
	qw422016.N().S(string(form.FileField("avatar", NewAttrs().Class("input").Accept("image/*").Data("upload_preview_target", "input").Data("action", "upload-preview#previewImage"))))
	qw422016.N().S(`
            <span class="for-screen-reader">Upload avatar</span>
          </div>

          <div class="btn avatar input--file txt-xx-large">
            `)
	qw422016.N().S(string(ImageTag(p.Ctx, "default-avatar.svg", NewAttrs().AriaHidden().Data("upload_preview_target", "image"))))
	qw422016.N().S(`
            <span class="for-screen-reader">Avatar</span>
          </div>
        </label>
      </fieldset>

      <div class="flex align-center gap">
        `)
	qw422016.N().S(string(TranslationButton(p.Ctx, "user_name")))
	qw422016.N().S(`
        <label class="flex align-center gap flex-item-grow txt-large input input--actor">
          `)
	qw422016.N().S(string(form.TextField("name", nil, NewAttrs().Class("input").Autocomplete("name").Placeholder("Name").Autofocus().Required(true).Data("1p-ignore", true))))
	qw422016.N().S(`
          `)
	qw422016.N().S(string(ImageTag(p.Ctx, "person.svg", NewAttrs().AriaHidden().Size(24).Class("colorize--black"))))
	qw422016.N().S(`
        </label>
      </div>

      <div class="flex align-center gap">
        `)
	qw422016.N().S(string(TranslationButton(p.Ctx, "email_address")))
	qw422016.N().S(`
        <label class="flex align-center gap flex-item-grow txt-large input input--actor">
          `)
	qw422016.N().S(string(form.EmailField("email_address", nil, NewAttrs().Class("input").Autocomplete("username").Placeholder("Email address").Required(true))))
	qw422016.N().S(`
          `)
	qw422016.N().S(string(ImageTag(p.Ctx, "email.svg", NewAttrs().AriaHidden().Size(24).Class("colorize--black"))))
	qw422016.N().S(`
        </label>
      </div>

      <div class="flex align-center gap">
        `)
	qw422016.N().S(string(TranslationButton(p.Ctx, "password")))
	qw422016.N().S(`
        <label class="flex align-center gap flex-item-grow txt-large input input--actor">
          `)
	qw422016.N().S(string(form.PasswordField("password", NewAttrs().Class("input").Autocomplete("new-password").Placeholder("Password").Required(true).Maxlength(72))))
	qw422016.N().S(`
          `)
	qw422016.N().S(string(ImageTag(p.Ctx, "password.svg", NewAttrs().AriaHidden().Size(24).Class("colorize--black"))))
	qw422016.N().S(`
        </label>
      </div>

      `)
	BeginCapture(qw422016)

	qw422016.N().S(`
        `)
	qw422016.N().S(string(ImageTag(p.Ctx, "check.svg", NewAttrs().AriaHidden())))
	qw422016.N().S(`
        <span class="for-screen-reader">Save</span>
`)
	capture2 := EndCapture(qw422016)

	qw422016.N().S(string(Button(capture2, NewAttrs().Class("btn btn--reversed center txt-large").Type("submit"))))
	qw422016.N().S(`    </div>
  </section>
`)
	capture1 := EndCapture(qw422016)

	qw422016.N().S(string(FormWithBlock(capture1, form)))
	qw422016.N().S(`
`)
	StreamAccountsHelpContact(qw422016, p.Ctx, p.HelpContact)
	qw422016.N().S(`
`)
}

func (p *UsersNew) WriteContent(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamContent(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *UsersNew) Content() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteContent(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
