// Code generated by qtc from "users_sidebars_rooms_direct_placeholder.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamUsersSidebarsRoomsDirectPlaceholder(qw422016 *qt422016.Writer, ctx *ViewContext, user *UserSummary) {
	BeginCapture(qw422016)

	qw422016.N().S(`
  <span class="avatar">
    `)
	qw422016.N().S(string(ImageTag(ctx, user.AvatarPath, NewAttrs().AriaHidden())))
	qw422016.N().S(`
  </span>

  <span class="direct__author flex align-center gap max-width min-width border-radius txt-small">
    <span class="txt-nowrap overflow-ellipsis">
      <span class="for-screen-reader">Start a ping with</span>
      `)
	qw422016.E().S(user.FirstName())
	qw422016.N().S(`
    </span>
  </span>
`)
	capture1 := EndCapture(qw422016)

	qw422016.N().S(string(ButtonToBlock(capture1, RoomsDirectsWithUser(user.ID), NewAttrs().Class("direct borderless fill-transparent unpad"))))
}

func WriteUsersSidebarsRoomsDirectPlaceholder(qq422016 qtio422016.Writer, ctx *ViewContext, user *UserSummary) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamUsersSidebarsRoomsDirectPlaceholder(qw422016, ctx, user)
	qt422016.ReleaseWriter(qw422016)
}

func UsersSidebarsRoomsDirectPlaceholder(ctx *ViewContext, user *UserSummary) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteUsersSidebarsRoomsDirectPlaceholder(qb422016, ctx, user)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
