// Code generated by qtc from "users_autocompletables_template.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamUsersAutocompletablesTemplate(qw422016 *qt422016.Writer, ctx *ViewContext) {
	qw422016.N().S(`<template id="autocompletable-user">
  <div class="autocomplete__pill max-width" data-value="" tabindex="0">
    <img class="avatar flex-item-no-shrink" data-content="avatar" src="" />
    <span class="autocomplete-field__selected-value-text overflow-ellipsis flex-item-grow" data-content="label"></span>

    <button type="button" data-action="autocomplete#remove:prevent" data-value="" tabindex="-1" class="btn btn--plain txt-small translucent flex-item-no-shrink">
      `)
	StreamImageTag(qw422016, ctx, "remove-circle.svg", NewAttrs().AriaHidden().Class("colorize--black"))
	qw422016.N().S(`
      <span class="for-screen-reader">Remove <span data-content="screenReaderLabel"></span></span>
    </button>
  </div>
</template>
`)
}

func WriteUsersAutocompletablesTemplate(qq422016 qtio422016.Writer, ctx *ViewContext) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamUsersAutocompletablesTemplate(qw422016, ctx)
	qt422016.ReleaseWriter(qw422016)
}

func UsersAutocompletablesTemplate(ctx *ViewContext) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteUsersAutocompletablesTemplate(qb422016, ctx)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
