// Code generated by qtc from "users_avatars_show_svg.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import "unicode/utf8"

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamUsersAvatarsShowSvg(qw422016 *qt422016.Writer, userID int64, initials string) {
	qw422016.N().S(`<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
  viewBox="0 0 512 512" class="avatar" aria-hidden="true">
  <defs>
    <clipPath id="porthole">
      <circle cx="50%" cy="50%" r="50%" />
    </clipPath>
  </defs>

  <g>
    <rect width="100%" height="100%" rx="50" fill="`)
	qw422016.E().S(AvatarBackgroundColor(userID))
	qw422016.N().S(`" />

    <text x="50%" y="50%" fill="#FFFFFF"
      text-anchor="middle" dy="0.35em"
      `)
	if utf8.RuneCountInString(initials) >= 3 {
		qw422016.N().S(`textLength="85%" lengthAdjust="spacingAndGlyphs"`)
	}
	qw422016.N().S(`
      font-family="-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica, Arial, sans-serif"
      font-size="230"
      font-weight="800"
      letter-spacing="-5">
      `)
	qw422016.E().S(initials)
	qw422016.N().S(`
    </text>
  </g>
</svg>
`)
}

func WriteUsersAvatarsShowSvg(qq422016 qtio422016.Writer, userID int64, initials string) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamUsersAvatarsShowSvg(qw422016, userID, initials)
	qt422016.ReleaseWriter(qw422016)
}

func UsersAvatarsShowSvg(userID int64, initials string) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteUsersAvatarsShowSvg(qb422016, userID, initials)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
