// Code generated by qtc from "users_push_subscriptions_push_subscription.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamUsersPushSubscriptionsPushSubscription(qw422016 *qt422016.Writer, ctx *ViewContext, pushSubscription *PushSubscription) {
	qw422016.N().S(`<li class="flex flex-column margin-none membership-item">
  <span class="overflow-ellipsis txt-primary txt-undecorated">
    <strong>`)
	qw422016.E().S(pushSubscription.Browser)
	qw422016.N().S(` `)
	qw422016.E().S(pushSubscription.Version)
	qw422016.N().S(` on `)
	qw422016.E().S(pushSubscription.Platform)
	qw422016.N().S(`</strong><br>
  </span>

  <span class="flex align-start gap txt-small">
    <span>`)
	qw422016.E().S(pushSubscription.Endpoint)
	qw422016.N().S(`</span>

    <span class="flex align-center gap">
      `)
	BeginCapture(qw422016)

	qw422016.N().S(`
        `)
	StreamImageTag(qw422016, ctx, "notification-bell-everything.svg", NewAttrs().AriaHidden().Size(20))
	qw422016.N().S(`
        <span class="for-screen-reader">Send test notification</span>
`)
	capture1 := EndCapture(qw422016)

	qw422016.N().S(string(ButtonToBlock(capture1, RouteUserPushSubscriptionTestNotifications(pushSubscription.ID), NewAttrs().Class("btn btn--reversed"))))
	qw422016.N().S(`
      `)
	BeginCapture(qw422016)

	qw422016.N().S(`
        `)
	StreamImageTag(qw422016, ctx, "minus.svg", NewAttrs().AriaHidden().Size(20))
	qw422016.N().S(`
        <span class="for-screen-reader">Delete subscription</span>
`)
	capture2 := EndCapture(qw422016)

	qw422016.N().S(string(ButtonToBlock(capture2, RouteUserPushSubscription(pushSubscription.ID), NewAttrs().Method("delete").Class("btn btn--negative"))))
	qw422016.N().S(`    </span>
  </span>
</li>
`)
}

func WriteUsersPushSubscriptionsPushSubscription(qq422016 qtio422016.Writer, ctx *ViewContext, pushSubscription *PushSubscription) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamUsersPushSubscriptionsPushSubscription(qw422016, ctx, pushSubscription)
	qt422016.ReleaseWriter(qw422016)
}

func UsersPushSubscriptionsPushSubscription(ctx *ViewContext, pushSubscription *PushSubscription) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteUsersPushSubscriptionsPushSubscription(qb422016, ctx, pushSubscription)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
