// Code generated by qtc from "users_sidebars_rooms_direct.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamUsersSidebarsRoomsDirect(qw422016 *qt422016.Writer, ctx *ViewContext, membership *SidebarDirect) {
	qw422016.N().S(`
  `)
	BeginCapture(qw422016)

	qw422016.N().S(`
`)
	if len(membership.Members) > 1 {
		qw422016.N().S(`      <div class="avatar__group">
`)
		for i := range min(4, len(membership.Members)) {
			qw422016.N().S(`          <span class="avatar">
            `)
			StreamImageTag(qw422016, ctx, membership.Members[i].AvatarPath, NewAttrs().Size(20).AriaHidden())
			qw422016.N().S(`
          </span>
`)
		}
		qw422016.N().S(`      </div>
`)
	} else {
		qw422016.N().S(`      <span class="avatar">
        `)
		StreamImageTag(qw422016, ctx, membership.Members[0].AvatarPath, NewAttrs().Size(48).AriaHidden())
		qw422016.N().S(`
      </span>
`)
	}
	qw422016.N().S(`
    <span class="direct__author flex align-center gap max-width min-width border-radius txt-small">
      <span class="txt-nowrap overflow-ellipsis">
        <span class="for-screen-reader">Ping with</span>
`)
	if len(membership.Members) > 1 {
		qw422016.N().S(`          `)
		qw422016.E().S(membership.MemberInitials())
		qw422016.N().S(`
`)
	} else {
		qw422016.N().S(`          `)
		qw422016.E().S(membership.Members[0].FirstName())
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`      </span>
    </span>
`)
	capture1 := EndCapture(qw422016)

	qw422016.N().S(string(LinkToRoom(capture1, membership.RoomID, NewAttrs().Class(membership.ClassNames()).ID(DomID("rooms_direct", membership.RoomID, "list")).Data("sorted_list_number", membership.UpdatedAtEpoch))))
}

func WriteUsersSidebarsRoomsDirect(qq422016 qtio422016.Writer, ctx *ViewContext, membership *SidebarDirect) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamUsersSidebarsRoomsDirect(qw422016, ctx, membership)
	qt422016.ReleaseWriter(qw422016)
}

func UsersSidebarsRoomsDirect(ctx *ViewContext, membership *SidebarDirect) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteUsersSidebarsRoomsDirect(qb422016, ctx, membership)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
