// Code generated by qtc from "users_sidebars_rooms_direct.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamUsersSidebarsRoomsDirect(qw422016 *qt422016.Writer, ctx *ViewContext, membership *SidebarDirect) {
}

func WriteUsersSidebarsRoomsDirect(qq422016 qtio422016.Writer, ctx *ViewContext, membership *SidebarDirect) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamUsersSidebarsRoomsDirect(qw422016, ctx, membership)
	qt422016.ReleaseWriter(qw422016)
}

func UsersSidebarsRoomsDirect(ctx *ViewContext, membership *SidebarDirect) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteUsersSidebarsRoomsDirect(qb422016, ctx, membership)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
