// Code generated by qtc from "users_profiles_show.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func (p *UsersProfilesShow) StreamHead(qw422016 *qt422016.Writer) {
}

func (p *UsersProfilesShow) WriteHead(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamHead(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *UsersProfilesShow) Head() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteHead(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *UsersProfilesShow) StreamNav(qw422016 *qt422016.Writer) {
}

func (p *UsersProfilesShow) WriteNav(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamNav(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *UsersProfilesShow) Nav() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteNav(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *UsersProfilesShow) StreamContent(qw422016 *qt422016.Writer) {
}

func (p *UsersProfilesShow) WriteContent(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamContent(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *UsersProfilesShow) Content() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteContent(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
