// Code generated by qtc from "users_push_subscriptions_index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func (p *UsersPushSubscriptionsIndex) StreamHead(qw422016 *qt422016.Writer) {
}

func (p *UsersPushSubscriptionsIndex) WriteHead(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamHead(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *UsersPushSubscriptionsIndex) Head() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteHead(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *UsersPushSubscriptionsIndex) StreamNav(qw422016 *qt422016.Writer) {
	qw422016.N().S(`  <div class="flex-item-justify-start">
    `)
	qw422016.N().S(string(LinkBackToLastRoomVisited(p.Ctx)))
	qw422016.N().S(`
  </div>
`)
}

func (p *UsersPushSubscriptionsIndex) WriteNav(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamNav(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *UsersPushSubscriptionsIndex) Nav() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteNav(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *UsersPushSubscriptionsIndex) StreamContent(qw422016 *qt422016.Writer) {
	qw422016.N().S(`<section class="panel panel--wide flex flex-column gap">
  <h1 class="txt-align-center txt-large margin-none">Push Notification Subscriptions</h1>
  <div class="pad-inline fill-shade border-radius" id="push_subscriptions">
    <menu class="pad flex flex-column gap">
      `)
	for i := range p.PushSubscriptions {
		StreamUsersPushSubscriptionsPushSubscription(qw422016, p.Ctx, &p.PushSubscriptions[i])
	}
	qw422016.N().S(`    </menu>
  </div>
</section>
`)
}

func (p *UsersPushSubscriptionsIndex) WriteContent(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamContent(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *UsersPushSubscriptionsIndex) Content() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteContent(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
