// Code generated by qtc from "users_profiles_transfer.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamUsersProfilesTransfer(qw422016 *qt422016.Writer, ctx *ViewContext, user *UserSummary, transferID string) {
	url := ctx.URL(RouteSessionTransfer(transferID))

	qw422016.N().S(`
<fieldset>
  <legend class="gap">
    `)
	qw422016.N().S(string(ImageTag(ctx, "laptop.svg", NewAttrs().AriaHidden().Size(36).Class("colorize--black"))))
	qw422016.N().S(`
    `)
	qw422016.N().S(string(ImageTag(ctx, "transfer.svg", NewAttrs().AriaHidden().Size(36).Class("colorize--black"))))
	qw422016.N().S(`
    `)
	qw422016.N().S(string(ImageTag(ctx, "mobile-phone.svg", NewAttrs().AriaHidden().Size(36).Class("colorize--black"))))
	qw422016.N().S(`
  </legend>


  <div class="flex flex-column gap">
`)
	if !ctx.IsCurrentUser(user.ID) {
		qw422016.N().S(`      <div class="flex align-center gap justify-center">
        `)
		qw422016.N().S(string(ImageTag(ctx, "crown.svg", NewAttrs().Size(16).AriaHidden().Class("flex-item-no-shrink colorize--black"))))
		qw422016.N().S(`
        <label for="session_transfer_url">Share to get them back into their account</label>
      </div>
`)
	} else {
		qw422016.N().S(`      <label for="session_transfer_url" class="for-screen-reader">Use this link to login automatically on another device</label>
`)
	}
	qw422016.N().S(`
    <input type="text" class="input" value="`)
	qw422016.E().S(url)
	qw422016.N().S(`" id="session_transfer_url" readonly>

    <div class="flex align-center center gap">
      `)
	BeginCapture(qw422016)

	qw422016.N().S(`
        <span class="for-screen-reader">Show auto-login QR code</span>
        `)
	qw422016.N().S(string(ImageTag(ctx, "qr-code.svg", NewAttrs().AriaHidden().Size(20).Class("colorize--black"))))
	qw422016.N().S(`
`)
	capture1 := EndCapture(qw422016)

	qw422016.N().S(string(LinkToZoomQrCode(capture1, url)))
	qw422016.N().S(`
      `)
	BeginCapture(qw422016)

	qw422016.N().S(`
        <span class="for-screen-reader">Copy auto-login link</span>
        `)
	qw422016.N().S(string(ImageTag(ctx, "copy-paste.svg", NewAttrs().AriaHidden().Size(20).Class("flex-item-no-shrink colorize--black"))))
	qw422016.N().S(`
`)
	capture2 := EndCapture(qw422016)

	qw422016.N().S(string(ButtonToCopyToClipboard(capture2, url)))
	qw422016.N().S(`
      `)
	BeginCapture(qw422016)

	qw422016.N().S(`
        <span class="for-screen-reader">Share auto-login link</span>
        `)
	qw422016.N().S(string(ImageTag(ctx, "share.svg", NewAttrs().AriaHidden().Size(20).Class("flex-item-no-shrink colorize--black"))))
	qw422016.N().S(`
`)
	capture3 := EndCapture(qw422016)

	qw422016.N().S(string(WebShareSessionButton(capture3, url, "Your sign-in link", "This is your own private sign-in URL, DO NOT SHARE IT. Use it to sign-in on another device or if you get locked out.")))
	qw422016.N().S(`    </div>
  </div>
</fieldset>
`)
}

func WriteUsersProfilesTransfer(qq422016 qtio422016.Writer, ctx *ViewContext, user *UserSummary, transferID string) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamUsersProfilesTransfer(qw422016, ctx, user, transferID)
	qt422016.ReleaseWriter(qw422016)
}

func UsersProfilesTransfer(ctx *ViewContext, user *UserSummary, transferID string) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteUsersProfilesTransfer(qb422016, ctx, user, transferID)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
