// Code generated by qtc from "welcome_show.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func (p *WelcomeShow) StreamHead(qw422016 *qt422016.Writer) {
}

func (p *WelcomeShow) WriteHead(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamHead(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *WelcomeShow) Head() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteHead(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *WelcomeShow) StreamSidebar(qw422016 *qt422016.Writer) {
	qw422016.N().S(string(SidebarTurboFrameTag(Ptr(RouteUserSidebar()), "")))
}

func (p *WelcomeShow) WriteSidebar(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamSidebar(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *WelcomeShow) Sidebar() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteSidebar(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *WelcomeShow) StreamContent(qw422016 *qt422016.Writer) {
	qw422016.N().S(`<div id="message-area" class="message-area">
  <div class="message-area--empty min-width center">
    <figure class="center pad">
      `)
	qw422016.N().S(string(ImageTag(p.Ctx, "messages-empty.svg", NewAttrs().AriaHidden().Class("colorize--black translucent"))))
	qw422016.N().S(`
      <span class="for-screen-reader">`)
	qw422016.E().S(p.CurrentUserName)
	qw422016.N().S(`</span>
    </figure>
  </div>
</div>
`)
}

func (p *WelcomeShow) WriteContent(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamContent(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *WelcomeShow) Content() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteContent(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
